# Generated by Django 4.1.1 on 2022-10-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document_id',
            field=models.CharField(default='g', max_length=225),
        ),
    ]
