# Generated by Django 4.1.2 on 2022-10-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document_id',
            field=models.CharField(default='', max_length=225),
        ),
    ]
