# Generated by Django 4.1.2 on 2022-10-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_document_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_picture',
            field=models.URLField(blank=True, default=''),
        ),
    ]
