# Generated by Django 4.1.1 on 2022-10-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_document_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document_id',
            field=models.CharField(max_length=225),
        ),
    ]
