# Generated by Django 4.1.1 on 2022-10-07 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_document_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='document_id',
        ),
    ]
